import { test,expect } from '@playwright/test';
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('hotlah:style-seen','1'));});
test('customer can browse, filter, save and send a request',async({page})=>{
 await page.goto('/');await expect(page.locator('html')).toHaveAttribute('data-hydrated','true');await expect(page.getByRole('heading',{name:'Find your next set.'})).toBeVisible();
 await page.getByRole('button',{name:'Cat eye',exact:true}).click();await expect(page.locator('.service-card')).toHaveCount(1);
 await page.getByRole('button',{name:'All styles',exact:true}).click();await page.getByRole('button',{name:'Save service'}).first().click();
 await page.getByRole('link',{name:'French gel manicure',exact:true}).click();await expect(page.getByRole('heading',{name:'Find your time'})).toBeVisible();
 await page.locator('.availability-table button:not([disabled])').first().click();await page.getByRole('button',{name:'Request',exact:true}).click();
 await page.getByRole('button',{name:'Explore as a customer'}).click();await page.getByRole('button',{name:'Request',exact:true}).click();
 await page.getByLabel('A note for your nailist (optional)').fill('I would love a shorter almond shape.');await page.getByRole('button',{name:'Send booking request'}).click();
 await expect(page.getByText('Pending approval',{exact:true})).toBeVisible();await expect(page.getByText('I would love a shorter almond shape.')).toBeVisible();
 await page.getByRole('textbox',{name:'Message',exact:true}).fill('Thank you, looking forward to it.');await page.getByRole('button',{name:'Send message'}).click();await expect(page.getByText('Thank you, looking forward to it.')).toBeVisible();
 await page.getByRole('button',{name:'Cancel booking',exact:true}).click();await page.getByRole('button',{name:'Yes, cancel booking'}).click();await expect(page.getByText('Cancelled',{exact:true})).toBeVisible();
});
test('subscription gate redacts details and blocks direct access',async({page})=>{
 await page.request.post('/api/demo/login',{data:{role:'merchant'}});await page.request.post('/api/demo/access',{data:{restricted:true}});
 try{await page.goto('/merchant');await expect(page.getByRole('heading',{name:'New booking request'}).first()).toBeVisible();const response=await page.request.get('/api/bookings?view=merchant');const {bookings}=await response.json();const locked=bookings.find((b:{locked:number;status:string})=>b.locked&&b.status==='pending');expect(locked).toBeTruthy();expect(Object.keys(locked).sort()).toEqual(['id','locked','status']);expect((await page.request.get(`/api/bookings/${locked.id}`)).status()).toBe(403);expect((await page.request.post(`/api/bookings/${locked.id}/status`,{data:{status:'approved'}})).status()).toBe(403);expect(bookings.some((b:{status:string;name?:string})=>b.status==='approved'&&b.name)).toBeTruthy();}finally{await page.request.post('/api/demo/access',{data:{restricted:false}});}
});
test('API requires authentication and withholds private contact information',async({request})=>{expect((await request.get('/api/bookings')).status()).toBe(401);const result=await request.get('/api/services/french-gel');const data=await result.json();expect(data.merchant).not.toHaveProperty('phone');expect(data.merchant).not.toHaveProperty('address');expect((await request.post('/api/demo/login',{data:{role:'customer'},headers:{Origin:'https://untrusted.example'}})).status()).toBe(403);});
test('sign-in only shows configured providers',async({page})=>{await page.goto('/account');await expect(page.locator('html')).toHaveAttribute('data-hydrated','true');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('button',{name:'Explore as a customer'})).toBeVisible();await expect(page.getByRole('button',{name:/Continue with Apple/})).toHaveCount(0);});
test('catalogue next availability corresponds to a requestable slot',async({request})=>{const {services}=await (await request.get('/api/catalog')).json();for(const service of services){if(!service.next_available)continue;const {slots}=await (await request.get(`/api/services/${service.id}/availability?date=${service.next_available.date}`)).json();expect(slots.some((s:{minute:number;available:boolean})=>s.minute===service.next_available.minute&&s.available)).toBe(true);}});
test('language switch and geographic region selector work',async({page})=>{await page.goto('/');await expect(page.locator('html')).toHaveAttribute('data-hydrated','true');await page.getByRole('button',{name:'Kuala Lumpur & Selangor',exact:true}).click();await expect(page.getByRole('button',{name:'Select Petaling',exact:true})).toBeVisible();await page.getByRole('button',{name:'Select Petaling',exact:true}).click();await expect(page.locator('.service-card')).toHaveCount(6);await page.getByRole('button',{name:'切换中文'}).click();await expect(page.getByRole('heading',{name:'找到下一款心动美甲。'})).toBeVisible();await expect(page.locator('html')).toHaveAttribute('lang','zh-Hans');});
test('responsive screens have no horizontal overflow',async({page})=>{await page.request.post('/api/demo/login',{data:{role:'customer'}});for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});for(const path of ['/','/services/french-gel','/bookings','/messages','/account']){await page.goto(path);await expect(page.locator('main')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}}});
