import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Home, Store, Navigation, ShieldCheck, Pencil } from 'lucide-react';
import type { Merchant, MerchantType } from '../lib/types';
import { MERCHANT_STYLES, STYLE_ZH } from '../lib/types';
import { useApp } from '../lib/context';
import { post } from '../lib/api';
import { ErrorNotice } from './ui';

type Profile = { name:string; area:string; work_types:MerchantType[]; shop_link:string; address:string; phone:string; bio:string; styles:string[]; hours:Merchant['hours']; policy:string; auto_approve:boolean };
const areas = ['Petaling Jaya','SS2, Petaling Jaya','Damansara','Subang Jaya','Kuala Lumpur','Shah Alam','Klang','Cheras','Ampang','Puchong','Gombak','Kajang','Banting','Sepang','Kuala Selangor','Hulu Selangor','Sabak Bernam'];
export function MerchantForm({initial,onSaved}:{initial?:Merchant;onSaved:()=>void|Promise<void>}) {
  const {t,lang,session}=useApp();
  const [profile,setProfile]=useState<Profile>(()=>({name:initial?.name??'',area:initial?.area??'Petaling Jaya',work_types:initial?.work_types?.length?initial.work_types:[initial?.type??'home'],shop_link:initial?.shop_link??'',address:initial?.address??'',phone:initial?.phone??'',bio:initial?.bio??'',styles:initial?.styles??[],hours:initial?.hours??{open:'10:00',close:'19:00',days:[1,2,3,4,5,6]},policy:initial?.policy??'Please arrive on time. Let me know as early as possible if you need to cancel.',auto_approve:!!initial?.auto_approve}));
  const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ready,setReady]=useState(false);
  const heading=useRef<HTMLHeadingElement>(null),form=useRef<HTMLFormElement>(null);
  const draftKey='hotlah:merchant-draft:'+session.user?.id;
  const labels=[t('Basics','基本信息'),t('Location','营业地点'),t('Your work','您的风格'),t('Bookings','预约设置'),t('Review','确认信息')];
  const titles=[t('Let’s start with you.','先认识一下您。'),t('Where do you work?','您在哪里营业？'),t('Make it feel like you.','展示您的独特风格。'),t('Set your own rhythm.','按自己的节奏工作。'),t(initial?'Ready to save your changes?':'A final look before you join.',initial?'准备保存修改了吗？':'加入前，再确认一下。')];
  const descriptions=[null,t('Your area helps customers find you. Your exact address stays private until their booking is approved.','地区帮助顾客找到您。详细地址仅在预约批准后向顾客公开。'),t('Choose your specialties. Photos and individual services come next, in your menu.','选择擅长款式。稍后在菜单中添加照片和具体服务。'),t('Start with your usual hours. Change these later or block time in your calendar.','先设置常规营业时间。之后可修改，或在日历中屏蔽时段。'),t('Everything here can be edited from your business page.','这里的所有信息都可以在经营页面中修改。')];
  useEffect(()=>{
    if(!initial)try {const saved=sessionStorage.getItem(draftKey);if(saved){const draft=JSON.parse(saved);if(typeof draft.name==='string'&&Array.isArray(draft.styles)&&Array.isArray(draft.hours?.days))setProfile(current=>({...current,...draft,work_types:Array.isArray(draft.work_types)&&draft.work_types.length?draft.work_types.slice(0,2):[draft.type??current.work_types[0]],shop_link:typeof draft.shop_link==='string'?draft.shop_link:''}));}} catch {}
    setReady(true);
  },[draftKey,initial]);
  useEffect(()=>{if(ready&&!initial)try{sessionStorage.setItem(draftKey,JSON.stringify(profile));}catch{}},[profile,ready,initial,draftKey]);
  const change=<K extends keyof Profile>(key:K,value:Profile[K])=>setProfile(p=>({...p,[key]:value}));
  const go=(next:number)=>{setStep(next);setError('');requestAnimationFrame(()=>{heading.current?.focus();heading.current?.scrollIntoView({block:'start',behavior:'instant'});});};
  const submit=async(e:React.FormEvent)=>{
    e.preventDefault();if(busy||!form.current?.reportValidity())return;
    if(step===0&&!profile.work_types.length){setError(t('Choose at least one way you work.','请至少选择一种经营方式。'));return;}
    if(step===2&&!profile.styles.length){setError(t('Choose at least one specialty.','请至少选择一种擅长款式。'));return;}
    if(step===3&&(!profile.hours.days.length||profile.hours.close<=profile.hours.open)){setError(t('Choose a working day and a closing time after opening.','请选择营业日，结束时间应晚于开始时间。'));return;}
    if(step<4){go(step+1);return;}
    setBusy(true);setError('');
    try {await post('/api/merchant',profile,initial?'PATCH':'POST');if(!initial)try{sessionStorage.removeItem(draftKey);}catch{}await onSaved();}
    catch(e){setError((e as Error).message);}finally{setBusy(false);}
  };
  const typeLabels={home:t('Home studio','家庭工作室'),studio:t('Nail studio','美甲店'),mobile:t('Mobile nailist','上门美甲师')};
  const workTypeLabel=profile.work_types.map(type=>typeLabels[type]).join(' · ');
  return <form ref={form} className="guided-form" onSubmit={submit}>
    <nav className="setup-progress" aria-label={t('Profile setup progress','资料设置进度')}><ol>{labels.map((label,i)=><li key={label} className={i===step?'current':i<step?'complete':''}><button type="button" disabled={busy||(!initial&&i>step)} aria-current={i===step?'step':undefined} onClick={()=>go(i)}><span>{i<step?<Check size={13}/>:i+1}</span>{label}</button></li>)}</ol></nav>
    <header className="guide-intro"><h2 ref={heading} tabIndex={-1}>{titles[step]}</h2>{descriptions[step]&&<p>{descriptions[step]}</p>}</header>
    <fieldset className="guide-fields" disabled={busy||!ready}>
      {step===0&&<><label className="field">{t('Studio / nailist name','工作室 / 美甲师名称')}<input autoComplete="organization" required minLength={2} maxLength={80} value={profile.name} onChange={e=>change('name',e.target.value)} placeholder={t('The name customers will know you by','顾客认识您的名称')}/></label><fieldset className="choice-list"><legend>{t('How do you work?','您的经营方式是？')}</legend><p className="choice-hint" id="work-types-hint">{t('Choose up to two.','最多选择两项。')}</p>{([{value:'home',icon:Home,description:t('A welcoming space in your own home.','在家中设立的美甲空间。')},{value:'studio',icon:Store,description:t('Customers visit your dedicated studio.','顾客到您的店铺接受服务。')},{value:'mobile',icon:Navigation,description:t('You travel to your customers.','您前往顾客指定地点提供服务。')}] as const).map(({value,icon:Icon,description})=>{const selected=profile.work_types.includes(value);return <label className={'choice-row '+(selected?'selected':'')} key={value}><Icon size={22}/><span><strong>{typeLabels[value]}</strong><small>{description}</small></span><input type="checkbox" name="business-type" value={value} aria-describedby="work-types-hint" checked={selected} disabled={!selected&&profile.work_types.length>=2} onChange={e=>change('work_types',e.target.checked?[...profile.work_types,value]:profile.work_types.filter(type=>type!==value))}/></label>;})}</fieldset></>}
      {step===1&&<><label className="field">{t('Area','地区')}<select value={profile.area} onChange={e=>change('area',e.target.value)}>{areas.map(a=><option key={a}>{a}</option>)}</select></label><label className="field">{t(profile.work_types.includes('mobile')?'Business base address':'Exact address',profile.work_types.includes('mobile')?'营业基地地址':'详细地址')}<textarea autoComplete="street-address" required minLength={5} maxLength={250} value={profile.address} onChange={e=>change('address',e.target.value)}/></label><div className="inline-help"><ShieldCheck size={20}/><p>{t('Only your area is public. Address and contact options unlock after booking approval.','仅地区会公开。批准预约后，顾客才可查看地址和联系方式。')}</p></div><label className="field">{t('Phone / WhatsApp (optional)','电话 / WhatsApp（选填）')}<input type="tel" autoComplete="tel" pattern="[+]?[0-9]{9,15}" value={profile.phone} onChange={e=>change('phone',e.target.value)} placeholder="+60123456789"/><small>{t('Include your country code, without spaces.','请包含国家代码，不要输入空格。')}</small></label><label className="field">{t('Any link to your business? (optional)','有商家相关链接吗？（选填）')}<input type="url" inputMode="url" autoComplete="url" maxLength={500} value={profile.shop_link} onChange={e=>change('shop_link',e.target.value)} placeholder="https://"/></label></>}
      {step===2&&<><fieldset><legend>{t('Your specialties — choose at least one','擅长款式（至少选择一项）')}</legend><div className="specialty-grid">{MERCHANT_STYLES.map(style=><label className={'chip check-chip '+(profile.styles.includes(style)?'selected':'')} key={style}><input type="checkbox" checked={profile.styles.includes(style)} onChange={e=>change('styles',e.target.checked?[...profile.styles,style]:profile.styles.filter(s=>s!==style))}/>{lang==='zh'?STYLE_ZH[style]:style}</label>)}</div></fieldset><label className="field">{t('A little about your work (optional)','介绍一下您的作品（选填）')}<textarea rows={4} maxLength={1200} value={profile.bio} onChange={e=>change('bio',e.target.value)} placeholder={t('Your approach, favourite techniques, or what makes a visit special.','介绍您的理念、擅长技法，或服务的独特之处。')}/><small>{t('Keep links and contact details out of public text.','请勿在公开介绍中填写链接或联系方式。')}</small></label></>}
      {step===3&&<><fieldset><legend>{t('Your usual working days','常规营业日')}</legend><div className="weekday-picker">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day,i)=><label className={profile.hours.days.includes(i)?'selected':''} key={day}><input type="checkbox" aria-label={day} checked={profile.hours.days.includes(i)} onChange={e=>change('hours',{...profile.hours,days:e.target.checked?[...profile.hours.days,i]:profile.hours.days.filter(d=>d!==i)})}/><span>{lang==='zh'?['日','一','二','三','四','五','六'][i]:day}</span></label>)}</div></fieldset><div className="merchant-hours-grid"><label className="field">{t('Open','开始')}<input type="time" required value={profile.hours.open} onChange={e=>change('hours',{...profile.hours,open:e.target.value})}/></label><label className="field">{t('Close','结束')}<input type="time" required value={profile.hours.close} onChange={e=>change('hours',{...profile.hours,close:e.target.value})}/></label></div><label className="toggle-row"><span><strong>{t('Automatically approve bookings','自动批准预约')}</strong><small>{t('Off: review each request yourself.','关闭时，由您逐一确认预约请求。')}</small></span><input role="switch" type="checkbox" checked={profile.auto_approve} onChange={e=>change('auto_approve',e.target.checked)}/></label><label className="field">{t('Booking and cancellation policy','预约及取消政策')}<textarea required minLength={10} maxLength={1500} rows={4} value={profile.policy} onChange={e=>change('policy',e.target.value)}/><small>{t('Use this wording or write your own. You can revise it later.','可使用默认内容或自行撰写，之后也可修改。')}</small></label></>}
      {step===4&&<><div className="review-profile"><div className="studio-monogram">{profile.name.slice(0,1)||'h.'}</div><h3>{profile.name}</h3><p>{workTypeLabel} · {profile.area}</p></div><div className="review-rows">{[
        [labels[0],profile.name+' · '+workTypeLabel],
        [labels[1],profile.address+(profile.phone?' · '+profile.phone:'')+(profile.shop_link?' · '+profile.shop_link:'')],
        [labels[2],profile.styles.map(s=>lang==='zh'?STYLE_ZH[s]??s:s).join(' · ')],
        [labels[3],[...profile.hours.days].sort().map(d=>lang==='zh'?['日','一','二','三','四','五','六'][d]:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]).join(', ')+' · '+profile.hours.open+'–'+profile.hours.close+' · '+(profile.auto_approve?t('Automatic approval','自动批准'):t('Manual approval','手动批准'))],
      ].map(([label,value],i)=><div key={label}><span><strong>{label}</strong><p>{value}</p></span><button type="button" className="icon-button" aria-label={t('Edit','编辑')+' '+label} onClick={()=>go(i)}><Pencil size={18}/></button></div>)}</div>{profile.bio&&<div className="review-text"><strong>{t('About your work','作品介绍')}</strong><p>{profile.bio}</p></div>}<div className="review-text"><strong>{t('Booking policy','预约政策')}</strong><p>{profile.policy}</p></div>{!initial&&<div className="notice"><strong>{t('What happens next?','接下来会怎样？')}</strong><p>{t('We’ll review your application. While you wait, add your first service and photo. Your studio goes public only after approval.','我们会审核您的申请。等待期间可添加第一项服务和照片。店铺仅在审核通过后公开。')}</p></div>}</>}
    </fieldset>
    {error&&<ErrorNotice message={error}/>}
    <div className="guide-actions">{step>0&&<button type="button" className="button secondary" disabled={busy} onClick={()=>go(step-1)}><ArrowLeft size={17}/>{t('Back','返回')}</button>}<button className="button primary" type="submit" disabled={busy}>{busy?t('Saving…','保存中…'):step===4?t(initial?'Save changes':'Submit for review',initial?'保存修改':'提交审核'):t('Continue','继续')}{!busy&&<ArrowRight size={17}/>}</button></div>
    <p className="guide-footnote">{initial?t('Changes apply when you save.','保存后修改才会生效。'):t('Free at launch. Your draft stays in this browser tab until you submit.','上线初期免费。提交前，草稿保留在当前浏览器标签页中。')}</p>
  </form>;
}
