import { Link } from 'react-router';
import { Heart,MapPin,ArrowUpRight } from 'lucide-react';
import { useApp } from '../lib/context';
import { money,STYLE_ZH,time,friendlyDate,localDate } from '../lib/types';
import type { Service } from '../lib/types';
export function ServiceCard({service:s,hideMerchant=false}:{service:Service;hideMerchant?:boolean}){
 const {lang,t,saved,toggleSaved}=useApp();
 return <article className="service-card"><div className="service-photo"><Link to={`/services/${s.id}`} tabIndex={-1} aria-hidden="true"><img src={s.image} alt="" width="1000" height="750" loading="lazy"/></Link><button className={`save-button ${saved.includes(s.id)?'saved':''}`} aria-label={saved.includes(s.id)?'Unsave service':'Save service'} aria-pressed={saved.includes(s.id)} onClick={()=>toggleSaved(s.id)}><Heart size={20} fill={saved.includes(s.id)?'currentColor':'none'}/></button>{!!s.promoted&&<span className="photo-label">{t('Featured','精选')}</span>}</div><div className="service-content"><div className="service-meta"><span>{lang==='zh'?STYLE_ZH[s.style]??s.style:s.style}</span><span>{s.duration} {t('min','分钟')}</span></div><Link className="service-title" to={`/services/${s.id}`}><h3>{lang==='zh'&&s.name_zh?s.name_zh:s.name}</h3><ArrowUpRight size={20}/></Link>{!hideMerchant&&<Link className="merchant-name" to={`/nailists/${s.merchant_id}`}>{s.merchant_name}</Link>}<p className="location-line"><MapPin size={14}/>{s.area}{s.distance!==undefined&&` · ${s.distance.toFixed(1)} km`}</p><p className={`next-availability ${s.next_available?'':'unavailable'}`}>{s.next_available?`${t('Next request','可预约')} · ${s.next_available.date===localDate()?t('Today','今天'):friendlyDate(s.next_available.date,lang)} · ${time(s.next_available.minute)}`:t('No times in the next 14 days','未来14天暂无时段')}</p><div className="service-bottom"><strong>{money(s.price)}</strong></div></div></article>;
}
