/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app\themes\merchant.mjs
 * Command: astryx theme build app\themes\merchant.mjs
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./hotlah-merchant.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const hotlahMerchantTheme: DefinedTheme;
