import { useState } from 'react';
import { Link,useSearchParams } from 'react-router';
import { Plus,Pencil,Check,Clock,ArrowRight,ImagePlus,CalendarDays } from 'lucide-react';
import { useApp } from '../lib/context';
import { useApi,post } from '../lib/api';
import type { Service,Merchant } from '../lib/types';
import { STYLE_ZH,money } from '../lib/types';
import { AuthRequired,Loading,ErrorNotice,Empty,HotlahTabs } from '../components/ui';
import { MerchantForm } from '../components/merchant-form';
import { ServiceEditor } from '../components/service-editor';

export default function Business(){
  const {t,lang,session,toast,refreshSession}=useApp();
  const [params,setParams]=useSearchParams();const tab=params.get('tab')??'menu';
  const data=useApi<{merchant:Merchant;services:Service[]}>(session.merchant?'/api/merchant':null);
  const insights=useApi<Record<string,number>>(session.merchant&&tab==='insights'?'/api/merchant/insights':null);
  const customers=useApi<{customers:{id:string;name:string;bookings:number;last_booking:string}[]}>(session.merchant&&tab==='customers'?'/api/merchant/customers':null);
  const [editing,setEditing]=useState<Service|null|undefined>(undefined),[discard,setDiscard]=useState(false);
  if(!session.user)return <AuthRequired merchant/>;
  if(!session.merchant)return <Empty title={t('Your business starts here','从这里开始您的事业')} description={t('Create your nailist profile, then build a menu customers can discover.','创建美甲师资料，再建立供顾客浏览的菜单。')} action={<Link to="/join" className="button primary">{t('Set up my studio','设置我的店铺')}<ArrowRight size={18}/></Link>}/>;
  if(editing!==undefined)return <div className="business-page">{discard&&<div className="discard-panel" role="alert"><h2>{t('Leave this service?','离开此服务？')}</h2><p>{t('Your unsaved changes will be lost.','未保存的修改将丢失。')}</p><div className="button-pair"><button className="button primary" onClick={()=>setDiscard(false)}>{t('Keep editing','继续编辑')}</button><button className="button secondary" onClick={()=>{setDiscard(false);setEditing(undefined);}}>{t('Discard changes','放弃修改')}</button></div></div>}<div hidden={discard}><ServiceEditor initial={editing??undefined} onCancel={()=>setDiscard(true)} onSaved={()=>{setEditing(undefined);data.refresh();toast(t('Service saved.','服务已保存。'));}}/></div></div>;
  const available=data.data?.services.filter(s=>s.active).length??0;
  return <div className="business-page">
    <header className="business-identity"><div className="studio-monogram">{session.merchant.name.slice(0,1)}</div><div><h1>{t('Your business','您的经营空间')}</h1><p>{session.merchant.name}</p><span className={'business-status '+(session.merchant.approved?'approved':'')}>{session.merchant.approved?<Check size={13}/>:<Clock size={13}/>} {session.merchant.approved?t('Approved studio','店铺已通过审核'):t('Application in review','申请审核中')}</span></div></header>
    {!session.merchant.approved&&<div className="notice onboarding-next"><strong>{params.has('welcome')?t('You’re in. Let’s build your menu.','申请已收到，开始建立菜单吧。'):t('Get ready while we review.','审核期间，做好开业准备。')}</strong><p>{t('Add a service and photo below. Your menu stays private until your studio is approved.','在下方添加服务和照片。店铺审核通过前，菜单不会公开。')}</p></div>}
    <HotlahTabs id="business" value={tab} onChange={value=>setParams({tab:value})} label={t('Business sections','经营空间栏目')} className="business-tabs" tabs={[['menu','Menu','服务菜单'],['profile','Profile','店铺资料'],['insights','Insights','经营数据'],['customers','Customers','顾客']].map(([value,en,zh])=>({value,label:t(en,zh)}))}/>
    <section id={`business-${tab}-panel`} role="tabpanel" aria-labelledby={`business-${tab}-tab`}>{data.error?<ErrorNotice message={data.error} retry={data.refresh}/>:data.loading?<Loading/>:tab==='profile'&&data.data?<><Link to="/merchant/calendar" className="profile-calendar-link"><CalendarDays size={19}/><span>{t('Block time or manage your calendar','屏蔽时段或管理日历')}</span><ArrowRight size={17}/></Link><MerchantForm key={data.data.merchant.id} initial={data.data.merchant} onSaved={async()=>{data.refresh();await refreshSession();toast(t('Profile saved.','资料已保存。'));}}/></>:tab==='menu'?<>
      <div className="menu-heading"><div><h2>{t('Your service menu','您的服务菜单')}</h2><p>{t(available+' available · '+(data.data?.services.length??0)+' total',available+' 项开放预约 · 共 '+(data.data?.services.length??0)+' 项')}</p></div><button className="button primary" onClick={()=>setEditing(null)}><Plus size={17}/>{t('Add service','添加服务')}</button></div>
      {!data.data?.services.length?<div className="menu-empty"><ImagePlus size={36} strokeWidth={1.4}/><h3>{t('Start with your favourite set.','从您最喜欢的款式开始。')}</h3><p>{t('One photo, a name and a price. Give customers their first reason to book you.','一张照片、一个名称和一个价格，让顾客有理由选择您。')}</p><button className="button primary full" onClick={()=>setEditing(null)}>{t('Create my first service','创建第一项服务')}<ArrowRight size={18}/></button></div>:<div className="merchant-menu-list">{data.data.services.map(s=><article key={s.id} className={'merchant-menu-item '+(!s.active?'is-hidden':'')}><img src={s.image} alt={s.name}/><div><span className="small muted">{lang==='zh'?STYLE_ZH[s.style]??s.style:s.style} · {s.duration} {t('min','分钟')}</span><h3>{lang==='zh'&&s.name_zh?s.name_zh:s.name}</h3><strong>{money(s.price)}</strong><span className="menu-visibility">{s.active?<Check size={12}/>:<Clock size={12}/>} {s.active?t('Available','可预约'):t('Hidden','已隐藏')}{!!s.promoted&&' · '+t('Featured','精选')}</span></div><button className="icon-button" aria-label={t('Edit ','编辑 ')+s.name} onClick={()=>setEditing(s)}><Pencil size={18}/></button></article>)}</div>}
      <p className="guide-footnote">{t('Edit prices, photos and availability anytime. Existing bookings keep their original details.','可随时编辑价格、照片和开放状态。已有预约保留原始信息。')}</p>
    </>:tab==='insights'?<>{insights.error?<ErrorNotice message={insights.error} retry={insights.refresh}/>:insights.loading?<Loading/>:<><h2>{t('A clearer picture of your growth','更清晰地了解您的成长')}</h2><p className="muted small">{t('Reach covers the last 30 days. Booking totals are all-time.','曝光按近30天统计，预约为累计数据。')}</p><div className="insights-table">{[['impressions','Discovery impressions','发现页曝光'],['views','Service views','服务浏览'],['ctr','Click-through rate','点击率'],['newCustomers','Unique new customers','独立新顾客'],['requests','Booking requests','预约请求'],['completed','Completed appointments','已完成预约']].map(([key,en,zh])=><div key={key}><span>{t(en,zh)}</span><strong>{insights.data?.[key]??0}{key==='ctr'?'%':''}</strong></div>)}</div></>}</>:tab==='customers'?<><h2>{t('People you’ve welcomed','与您相遇的顾客')}</h2>{customers.error?<ErrorNotice message={customers.error} retry={customers.refresh}/>:customers.loading?<Loading/>:<><div className="inbox-list">{customers.data?.customers.map(c=><div className="option-row" key={c.id}><span>{c.name}</span><span className="muted small">{c.bookings} {t('bookings','次预约')}</span></div>)}</div>{!customers.data?.customers.length&&<p className="quiet-state">{t('Your customer list will grow with your bookings.','随着预约增加，顾客名单也会不断成长。')}</p>}</>}</>:null}</section>
    {session.demo&&<details className="demo-tools"><summary>Local subscription preview</summary><p>Simulate reaching the allowance. Confirmed appointments stay visible.</p><div className="button-pair"><button className="button secondary" onClick={async()=>{await post('/api/demo/access',{restricted:true});toast('Subscription gate enabled. Open Today to inspect it.');}}>Preview locked requests</button><button className="button secondary" onClick={async()=>{await post('/api/demo/access',{restricted:false});toast('Free launch access restored.');}}>Restore free access</button></div></details>}
  </div>;
}
