import { useState } from 'react';
import { useSearchParams } from 'react-router';
import { Plus,Pencil,Upload,ArrowRight } from 'lucide-react';
import { useApp } from '../lib/context';
import { useApi,post } from '../lib/api';
import type { Service,Merchant } from '../lib/types';
import { STYLES,money } from '../lib/types';
import { AuthRequired,Loading,ErrorNotice,Modal } from '../components/ui';
import { MerchantForm } from '../components/merchant-form';
export default function Business(){const {t,session,toast,refreshSession}=useApp();const [params,setParams]=useSearchParams();const tab=params.get('tab')??'menu';const data=useApi<{merchant:Merchant;services:Service[]}>(session.merchant?'/api/merchant':null);const insights=useApi<Record<string,number>>(session.merchant?'/api/merchant/insights':null);const customers=useApi<{customers:{id:string;name:string;bookings:number;last_booking:string}[]}>(session.merchant?'/api/merchant/customers':null);const [editing,setEditing]=useState<Service|null|undefined>(undefined),[image,setImage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 if(!session.user)return <AuthRequired merchant/>;const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await post(`/api/merchant/services${editing?`/${editing.id}`:''}`,{name:f.get('name'),name_zh:f.get('name_zh'),description:f.get('description'),price:Math.round(Number(f.get('price'))*100),duration:Number(f.get('duration')),buffer:Number(f.get('buffer')),image,style:f.get('style'),shape:f.get('shape'),active:f.get('active')==='on',promoted:f.get('promoted')==='on'},editing?'PATCH':'POST');setEditing(undefined);data.refresh();toast(t('Menu updated.','菜单已更新。'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const upload=async(file:File)=>{setBusy(true);setError('');try{const response=await fetch('/api/uploads',{method:'POST',body:file,headers:{'Content-Type':file.type}});const result=await response.json() as {url:string;error?:string};if(!response.ok)throw new Error(result.error);setImage(result.url);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="business-page"><header className="page-intro"><h1>{t('Your business','您的经营空间')}</h1><p>{session.merchant?.name}</p></header><div className="tabs">{[['menu','Menu','服务菜单'],['profile','Profile','店铺资料'],['insights','Insights','经营数据'],['customers','Customers','顾客']].map(([key,en,zh])=><button key={key} className={tab===key?'active':''} onClick={()=>setParams({tab:key})}>{t(en,zh)}</button>)}</div>{data.error&&<ErrorNotice message={data.error} retry={data.refresh}/>} {data.loading?<Loading/>:tab==='profile'&&data.data?<MerchantForm initial={data.data.merchant} onSaved={()=>{data.refresh();refreshSession();toast(t('Profile saved.','资料已保存。'));}}/>:tab==='menu'?<><div className="section-heading"><h2>{t('A menu with your signature','属于您的招牌菜单')}</h2><button className="button primary" onClick={()=>{setEditing(null);setImage('');setError('');}}><Plus size={18}/>{t('Add service','添加服务')}</button></div><div className="menu-list">{data.data?.services.map(s=><div key={s.id} className="menu-row"><img src={s.image} alt=""/><div><h3>{s.name}</h3><p>{money(s.price)} · {s.duration} {t('min','分钟')}</p><span className="small muted">{s.style} · {s.active?t('Available','可预约'):t('Hidden','已隐藏')}{!!s.promoted&&` · ${t('Featured','精选')}`}</span></div><button className="icon-button" aria-label={`Edit ${s.name}`} onClick={()=>{setEditing(s);setImage(s.image);setError('');}}><Pencil size={19}/></button></div>)}</div><p className="small muted">{t('Changes apply to new requests only. Existing bookings keep their original service and price.','修改仅适用于新请求，已有预约保留原服务与价格。')}</p></>:tab==='insights'?<><h2>{t('A clearer picture of your growth','更清晰地了解您的成长')}</h2><p className="muted">{t('Reach is measured over 30 days, with each visitor counted once per day. Booking totals are all-time.','曝光按近30天统计，每位访客每天计一次。预约为累计数据。')}</p><div className="insights-table">{[['impressions','Discovery impressions','发现页曝光'],['views','Service views','服务浏览'],['ctr','Click-through rate','点击率'],['newCustomers','Unique new customers','独立新顾客'],['requests','Booking requests','预约请求'],['completed','Completed appointments','已完成预约']].map(([key,en,zh])=><div key={key}><span>{t(en,zh)}</span><strong>{insights.data?.[key]??0}{key==='ctr'?'%':''}</strong></div>)}</div></>:tab==='customers'?<><h2>{t('People you’ve welcomed','与您相遇的顾客')}</h2><div className="inbox-list">{customers.data?.customers.map(c=><div className="option-row" key={c.id}><span>{c.name}</span><span className="muted small">{c.bookings} {t('bookings','次预约')}</span></div>)}</div>{!customers.data?.customers.length&&<p className="muted">{t('Your customer list will grow with your bookings.','随着预约增加，您的顾客名单也会不断成长。')}</p>}</>:null}
 {session.demo&&<details className="demo-tools"><summary>Local subscription preview</summary><p>Simulate reaching the allowance. Pending request details become inaccessible on the server. Confirmed appointments stay visible.</p><div className="button-pair"><button className="button secondary" onClick={async()=>{await post('/api/demo/access',{restricted:true});toast('Subscription gate enabled. Open Today to inspect it.');}}>Preview locked requests</button><button className="button secondary" onClick={async()=>{await post('/api/demo/access',{restricted:false});toast('Free launch access restored.');}}>Restore free access</button></div></details>}
 <Modal open={editing!==undefined} onOpenChange={v=>{if(!v)setEditing(undefined);}} title={t(editing?'Edit service':'Add your next signature',editing?'编辑服务':'添加招牌服务')}><form className="form-stack" onSubmit={save}><label className="upload-field">{image?<img src={image} alt="Service preview"/>:<Upload size={28}/>}<span>{t(image?'Change photo':'Upload a service photo','上传服务照片')}</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);}}/></label><label className="field">{t('Service name · English','服务名称 · 英文')}<input name="name" required minLength={3} maxLength={100} defaultValue={editing?.name}/></label><label className="field">{t('Service name · Chinese','服务名称 · 中文')}<input name="name_zh" maxLength={100} defaultValue={editing?.name_zh}/></label><label className="field">{t('What’s included','服务内容')}<textarea name="description" required minLength={10} maxLength={1600} defaultValue={editing?.description}/></label><div className="form-grid"><label className="field">{t('Price · MYR','价格 · MYR')}<input name="price" type="number" min="0" step="0.01" required defaultValue={editing?editing.price/100:88}/></label><label className="field">{t('Duration · minutes','时长 · 分钟')}<input name="duration" type="number" min="15" max="480" required defaultValue={editing?.duration??75}/></label><label className="field">{t('Buffer · minutes','间隔 · 分钟')}<input name="buffer" type="number" min="0" max="120" required defaultValue={editing?.buffer??15}/></label><label className="field">{t('Style','款式')}<select name="style" defaultValue={editing?.style}>{STYLES.map(s=><option key={s}>{s}</option>)}</select></label><label className="field">{t('Nail shape','甲型')}<select name="shape" defaultValue={editing?.shape??'Almond'}>{['Almond','Round','Squoval','Square','Coffin','Any'].map(s=><option key={s}>{s}</option>)}</select></label></div><label className="toggle-row"><span>{t('Available for booking','开放预约')}</span><input type="checkbox" name="active" defaultChecked={editing?!!editing.active:true}/></label><label className="toggle-row"><span>{t('Feature this service · free at launch','推广此服务 · 上线初期免费')}</span><input type="checkbox" name="promoted" defaultChecked={!!editing?.promoted}/></label>{error&&<ErrorNotice message={error}/>}<button className="button primary full" disabled={busy||!image}>{t(busy?'Saving…':'Save service',busy?'保存中…':'保存服务')}</button></form></Modal></div>;
}
