import { useState } from 'react';
import { Plus,Trash2 } from 'lucide-react';
import { useApp } from '../lib/context';
import { useApi,post } from '../lib/api';
import type { Booking } from '../lib/types';
import { localDate,time,friendlyDate } from '../lib/types';
import { PageHeader,AuthRequired,Loading,ErrorNotice,Modal } from '../components/ui';
import { BookingCard } from '../components/booking-card';
export default function Calendar(){const {session,t,lang,toast}=useApp();const [date,setDate]=useState(localDate()),[open,setOpen]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);const bookings=useApi<{bookings:Booking[]}>(session.merchant?'/api/bookings?view=merchant':null);const data=useApi<{blocks:{id:string;date:string;start_minute:number;end_minute:number}[]}>(session.merchant?'/api/merchant':null);if(!session.user)return <AuthRequired merchant/>;const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await post('/api/merchant/blocks',{date,start:f.get('start'),end:f.get('end')});data.refresh();setOpen(false);toast(t('Time blocked. Your availability is updated.','时段已屏蔽，可预约时间已更新。'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};return <div className="narrow-page"><PageHeader title={t('Your calendar','您的日历')} back="/merchant"/><div className="section-heading"><label className="field">{t('Choose date','选择日期')}<input type="date" min={localDate()} value={date} onChange={e=>setDate(e.target.value)}/></label><button className="button primary" onClick={()=>setOpen(true)}><Plus size={18}/>{t('Block time','屏蔽时段')}</button></div><h2>{friendlyDate(date,lang)}</h2>{bookings.loading?<Loading/>:<div className="booking-list motion-stagger">{bookings.data?.bookings.filter(b=>b.date===date&&b.status==='approved').map(b=><BookingCard key={b.id} booking={b} merchant/>)}</div>}<h3 className="subheading">{t('Unavailable times','不可预约时段')}</h3>{data.data?.blocks.filter(b=>b.date===date).map(b=><div key={b.id} className="option-row"><span>{time(b.start_minute)} – {time(b.end_minute)}</span><button className="icon-button" aria-label="Remove time block" onClick={async()=>{try{await post(`/api/merchant/blocks/${b.id}`,{},'DELETE');data.refresh();}catch(e){toast((e as Error).message);}}}><Trash2 size={18}/></button></div>)}{!data.data?.blocks.some(b=>b.date===date)&&<p className="muted">{t('No time blocks for this day. Your usual business hours apply.','当天没有屏蔽时段，按正常营业时间开放预约。')}</p>}{data.error&&<ErrorNotice message={data.error}/>}<Modal open={open} onOpenChange={setOpen} title={t('A little time off','留点休息时间')} description={t('Existing confirmed appointments cannot be blocked.','无法屏蔽已确认的预约时段。')}><form className="form-stack" onSubmit={save}><p>{friendlyDate(date,lang)}</p><div className="form-grid"><label className="field">{t('From','开始')}<input name="start" type="time" defaultValue="13:00" required/></label><label className="field">{t('Until','结束')}<input name="end" type="time" defaultValue="14:00" required/></label></div>{error&&<ErrorNotice message={error}/>}<button className="button primary full" disabled={busy}>{t('Block this time','屏蔽此时段')}</button></form></Modal></div>;}
