import { Link } from 'react-router';

export const meta=()=>[{title:'Data deletion · Hotlah'},{name:'description',content:'How to request deletion of a Hotlah account and associated personal data.'}];

export default function DataDeletion(){return <article className="legal-page">
  <header><p className="eyebrow">Account help</p><h1>Delete your Hotlah data</h1><p className="legal-summary">Hotlah does not currently offer a self-service deletion control. Use the contact process below to request deletion of your account and associated personal data.</p><p className="legal-updated">Last updated: 22 September 2026</p></header>
  <div className="legal-sections">
    <section className="legal-section"><h2>Request account deletion</h2><p>Send your request from the email address connected to your Hotlah account. This helps Hotlah verify that the request comes from the account owner.</p><ol><li>Email <span className="contact-placeholder">support_email_here</span>.</li><li>Use the subject <strong>Hotlah account deletion</strong>.</li><li>Include your Hotlah account email address and display name.</li><li>State whether you use Hotlah as a customer, a nailist, or both.</li><li>If you cannot email from the account address, explain why and provide enough information to verify account ownership.</li></ol><p>Do not send your password, social-provider password, access token, or authentication code.</p><div className="legal-callout"><strong>Contact address required</strong><p>Replace the placeholder with an active support email before submitting this page to Meta.</p></div></section>
    <section className="legal-section"><h2>What the request covers</h2><p>After verifying the request, Hotlah will delete or de-identify account data that it no longer needs. Depending on how you used the marketplace, this can include:</p><ul><li>Your account profile, linked social sign-in records, and active sessions</li><li>Your customer preferences, booking-related personal information, messages, notifications, and reviews</li><li>Your nailist profile, private contact details, services, availability, policies, and uploaded portfolio media</li></ul><p>Deleting Hotlah from Facebook or removing Facebook permissions does not by itself delete data stored by Hotlah. Use this request process as well.</p></section>
    <section className="legal-section"><h2>Information that may remain</h2><p>Hotlah may retain limited records when required by law or needed for security, fraud prevention, dispute handling, or the rights of another marketplace participant. Hotlah will limit access to retained records and keep them only for the applicable purpose.</p><p>Some de-identified or aggregated information may remain when it no longer identifies you.</p></section>
    <section className="legal-section"><h2>Before you send a request</h2><p>Account deletion can affect booking history, conversations, reviews, merchant services, and access to the platform. If you have an upcoming appointment or unresolved marketplace issue, include that context in your request.</p><p>For more information about Hotlah’s data practices, read the <Link to="/privacy">privacy policy</Link>.</p></section>
  </div>
</article>;}
