import { useEffect,useMemo,useState } from 'react';
import { useLoaderData } from 'react-router';
import type { Route } from './+types/explore';
import { Search,MapPin,ChevronDown,SlidersHorizontal,ArrowRight,Navigation,Check } from 'lucide-react';
import { serverApi } from '../lib/server.server';
import { useApp } from '../lib/context';
import { STYLES,STYLE_ZH,distanceKm } from '../lib/types';
import type { Service } from '../lib/types';
import { ServiceCard } from '../components/service-card';
import { Modal,Empty } from '../components/ui';
import { post } from '../lib/api';
import { NailStylePicker } from '../components/nail-style-picker';
import { LocationPicker } from '../components/location-picker';
const districtAreas:Record<string,string[]>={Petaling:['Petaling Jaya','Damansara','Subang','Shah Alam','Puchong'],'Hulu Langat':['Cheras','Kajang'],Gombak:['Gombak','Ampang'],'Kuala Langat':['Banting']};
export const meta=()=>[{title:'Hotlah — Find your next set'}];
export const loader=({request,context}:Route.LoaderArgs)=>serverApi<{services:Service[]}>(request,context,'/api/catalog');
export default function Explore(){
 const {services}=useLoaderData<typeof loader>();const {t,lang,toast}=useApp();
 const [query,setQuery]=useState(''),[style,setStyle]=useState('All'),[area,setArea]=useState('All areas'),[filters,setFilters]=useState(false),[location,setLocation]=useState(false),[onboard,setOnboard]=useState(false),[type,setType]=useState('all'),[shape,setShape]=useState('all'),[budget,setBudget]=useState(200),[sort,setSort]=useState('recommended'),[coords,setCoords]=useState<[number,number]|null>(null),[radius,setRadius]=useState(25);
 useEffect(()=>{if(!localStorage.getItem('hotlah:style-seen'))setOnboard(true);const s=localStorage.getItem('hotlah:style');if(s)setStyle(s);},[]);
 const choose=(s:string)=>{setStyle(s);localStorage.setItem('hotlah:style',s);localStorage.setItem('hotlah:style-seen','1');setOnboard(false);};
 const result=useMemo(()=>services.map(s=>({...s,distance:coords?distanceKm(coords[0],coords[1],s.lat,s.lng):undefined})).filter(s=>(style==='All'||s.style===style)&&(area==='All areas'||(districtAreas[area]??[area]).some(a=>s.area.includes(a)))&&(type==='all'||s.type===type)&&(shape==='all'||s.shape===shape)&&s.price<=budget*100&&(!coords||s.distance!<=radius)&&`${s.name} ${s.name_zh} ${s.merchant_name} ${s.area}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='price'?a.price-b.price:sort==='distance'?(a.distance??0)-(b.distance??0):Number(!!b.next_available)-Number(!!a.next_available)||b.promoted-a.promoted),[services,style,area,type,shape,budget,query,coords,radius,sort]);
 useEffect(()=>{const ids=[...new Set(result.map(s=>s.merchant_id))];ids.forEach(merchantId=>post('/api/events',{merchantId,kind:'impression'}).catch(()=>{}));},[result]);
 return <div className="explore-page"><section className="discovery-intro"><button className="location-selector" onClick={()=>setLocation(true)}><MapPin size={16}/>{area==='All areas'?t('Kuala Lumpur & Selangor','吉隆坡及雪兰莪'):area}<ChevronDown size={15}/></button><h1>{t('Find your next set.','找到下一款心动美甲。')}</h1><div className="search-row"><label className="search-field"><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Try “French”, a nailist or an area','搜索款式、美甲师或地区')} aria-label={t('Search services','搜索服务')}/></label><button className="filter-button" onClick={()=>setFilters(true)} aria-label={t('Filters','筛选')}><SlidersHorizontal size={22}/><span>{t('Filters','筛选')}</span></button></div></section><div className="style-strip" aria-label="Nail styles"><button className="chip" aria-haspopup="dialog" onClick={()=>setOnboard(true)}>{t('Choose a style','选择款式')}<ChevronDown size={14}/></button>{['All',...STYLES].map(s=><button key={s} className={`chip ${style===s?'selected':''}`} aria-pressed={style===s} onClick={()=>choose(s)}>{s==='All'?t('All styles','所有款式'):lang==='zh'?STYLE_ZH[s]:s}</button>)}</div><section className="results-section"><div className="section-heading"><div><h2>{t(coords?'Lovely nails, nearby':'A little local discovery',coords?'身边的心动美甲':'发现本地美甲好店')}</h2><p className="muted small">{result.length} {t('services to make your own','项服务，打造专属风格')}</p></div><select className="sort-select" aria-label="Sort services" value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">{t('Recommended','推荐排序')}</option><option value="price">{t('Price: low to high','价格从低到高')}</option>{coords&&<option value="distance">{t('Nearest first','距离最近')}</option>}</select></div>{result.length?<div className="service-grid">{result.map(s=><ServiceCard service={s} key={s.id}/>)}</div>:<Empty title={t('A fresh search?','换个搜索方式？')} description={t('Try another style or widen your area to discover more nailists.','试试其他款式或扩大搜索地区。')} action={<button className="button secondary" onClick={()=>{setQuery('');choose('All');setArea('All areas');setType('all');setShape('all');setBudget(200);setCoords(null);}}>{t('Reset filters','重置筛选')}</button>}/>}</section><div className="discovery-spacer" aria-hidden="true"/>
 <NailStylePicker open={onboard} value={style} onChoose={choose} onOpenChange={open=>{setOnboard(open);if(!open)localStorage.setItem('hotlah:style-seen','1');}}/>
 {location&&<LocationPicker value={{area,coords,radius}} onClose={()=>setLocation(false)} onApply={next=>{setArea(next.area);setCoords(next.coords);setRadius(next.radius);setSort(next.coords?'distance':'recommended');setLocation(false);}}/>}
 <Modal open={filters} onOpenChange={setFilters} title={t('Make it your kind','找到您的专属风格')}><div className="form-stack"><label className="field">{t('Studio type','店铺类型')}<select value={type} onChange={e=>setType(e.target.value)}><option value="all">{t('All nailists','全部美甲师')}</option><option value="home">{t('Home studio','家庭工作室')}</option><option value="studio">{t('Nail studio','美甲店')}</option><option value="mobile">{t('Mobile nailist','上门服务')}</option></select></label><label className="field">{t('Nail shape','甲型')}<select value={shape} onChange={e=>setShape(e.target.value)}>{['all','Almond','Round','Squoval','Square','Coffin','Any'].map(s=><option key={s} value={s}>{s==='all'?t('Any shape','所有甲型'):s}</option>)}</select></label><label className="field">{t('Maximum price','最高价格')} — RM {budget}<input type="range" min="50" max="300" step="10" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><button className="button primary full" onClick={()=>setFilters(false)}>{t(`Show ${result.length} services`,`查看 ${result.length} 项服务`)}<ArrowRight size={18}/></button></div></Modal></div>;
}
