import { Link } from 'react-router';

export const meta=()=>[{title:'Privacy policy · Hotlah'},{name:'description',content:'How Hotlah collects, uses, shares, retains and protects personal information.'}];

export default function Privacy(){return <article className="legal-page">
  <header><p className="eyebrow">Legal</p><h1>Privacy policy</h1><p className="legal-summary">This policy explains how Hotlah handles personal information when you browse the marketplace, create an account, book a service, or offer nail services.</p><p className="legal-updated">Last updated: 22 September 2026</p></header>
  <div className="legal-sections">
    <section className="legal-section"><h2>Information Hotlah collects</h2><p>Hotlah collects information you provide, information created through marketplace activity, and limited technical information needed to operate the service.</p>
      <h3>Account and profile information</h3><ul><li>Your name, email address, profile image, account identifier, and sign-in status</li><li>For nailists: studio or business name, service area, business type, biography, address, phone number, specialties, working hours, booking policy, services, prices, and portfolio photos</li></ul>
      <h3>Information from sign-in providers</h3><p>If you continue with Google, Facebook, or another enabled provider, Hotlah receives account information that provider makes available. This can include your provider account identifier, name, email address, email-verification status, and profile image. Hotlah also stores the account-link and authentication tokens needed to maintain your sign-in.</p>
      <h3>Marketplace activity</h3><ul><li>Booking requests, appointment details, selected services, dates, times, prices, and booking status</li><li>Messages, reviews, notifications, saved preferences, availability blocks, and account or merchant settings</li><li>Interactions such as service impressions, profile views, and call or WhatsApp actions</li></ul>
      <h3>Device and location information</h3><p>Hotlah processes session information such as your Internet Protocol address and browser user agent for authentication and security. If you allow browser location access, Hotlah uses your approximate coordinates to filter nearby results. You can search by area without sharing device location.</p>
    </section>
    <section className="legal-section"><h2>Why Hotlah uses this information</h2><p>Hotlah uses personal information to operate the marketplace and support the relationship between customers and nailists.</p><ul><li>Create and secure accounts</li><li>Display approved nailist profiles and service menus</li><li>Process booking requests, messages, notifications, reviews, and availability</li><li>Share approved appointment details, including private contact or address information when the product says it will</li><li>Measure service discovery and marketplace engagement</li><li>Prevent misuse, investigate errors, enforce platform rules, and protect users</li><li>Meet applicable legal obligations</li></ul></section>
    <section className="legal-section"><h2>How information is shared</h2><p>Hotlah shares information only as needed to operate the service, provide requested marketplace features, or comply with legal obligations.</p><ul><li><strong>Customers and nailists:</strong> Profile, service, booking, review, and conversation information is shared with the people involved. A nailist’s exact address and phone contact remain restricted until the booking reaches the required approval state.</li><li><strong>Service providers:</strong> Infrastructure, database, file storage, authentication, social sign-in, and email-delivery providers process information for Hotlah. Current integrations can include Cloudflare, Better Auth, Google, Facebook, and Resend.</li><li><strong>Safety and legal requests:</strong> Hotlah may disclose information when required by law or when necessary to protect the service, its users, or others.</li></ul><p>Hotlah does not currently sell personal information or process customer payments for nail services. Customers pay nailists at the appointment.</p></section>
    <section className="legal-section"><h2>Retention</h2><p>Hotlah keeps personal information while your account is active and as needed to provide the marketplace. Retention can continue when records are needed for security, dispute handling, fraud prevention, backups, or legal obligations. Hotlah removes or de-identifies information when it is no longer needed, subject to those limits.</p></section>
    <section className="legal-section"><h2>Security</h2><p>Hotlah uses reasonable technical and organizational safeguards designed for the service. These include authenticated access, role and ownership checks, restricted private booking details, secure session cookies, and access controls around stored data. No online service can guarantee absolute security.</p></section>
    <section className="legal-section"><h2>Your choices and deletion requests</h2><p>You can choose which social provider to use, decline browser location access, and update available profile information in the product. Hotlah does not currently offer self-service account deletion.</p><p>To request deletion, follow the steps on the <Link to="/data-deletion">Hotlah data deletion page</Link>.</p></section>
    <section className="legal-section"><h2>Contact Hotlah</h2><p>Send privacy questions or requests to <span className="contact-placeholder">support_email_here</span>.</p><div className="legal-callout"><strong>Contact address required</strong><p>Replace this placeholder with an active support email before publishing these pages for platform review.</p></div></section>
  </div>
</article>;}
